name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Thanks for contacting me! This issue is marked as stale because no one has commented recently.'
        stale-pr-message: ''
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: ''
